In [1]:
!pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/
!python -m pip install -U pip
!pip -V
!pip install sklearn pandas

Writing to /root/.config/pip/pip.conf
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already up-to-date: pip in /usr/local/lib/python3.6/dist-packages (20.2.4)
pip 20.2.4 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: sklearn in /usr/local/lib/python3.6/dist-packages (0.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (1.1.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (from sklearn) (0.23.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas) (2020.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.6/dist-packages (from pandas) (1.18.5)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->sklearn) (2.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->sklearn) (0.17.0)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.6/dist-packages (from scikit-learn->sklearn) (1.5.3)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7.3->pandas) (1.11.0)

In [2]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)

1.15.4
sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
matplotlib 3.3.2
numpy 1.18.5
pandas 1.1.3
sklearn 0.23.2
tensorflow 1.15.4
tensorflow.python.keras.api._v1.keras 2.2.4-tf

In [3]:
# https://storage.googleapis.com/tf-datasets/titanic/train.csv
# https://storage.googleapis.com/tf-datasets/titanic/eval.csv

train_file = './data/titanic/train.csv'
eval_file = './data/titanic/eval.csv'

train_df = pd.read_csv(train_file)
eval_df = pd.read_csv(eval_file)

print(train_df.head())
print(eval_df.head())

   survived     sex   age  n_siblings_spouses  parch     fare  class     deck  \
0         0    male  22.0                   1      0   7.2500  Third  unknown
1         1  female  38.0                   1      0  71.2833  First        C
2         1  female  26.0                   0      0   7.9250  Third  unknown
3         1  female  35.0                   1      0  53.1000  First        C
4         0    male  28.0                   0      0   8.4583  Third  unknown

   embark_town alone
0  Southampton     n
1    Cherbourg     n
2  Southampton     y
3  Southampton     n
4   Queenstown     y
   survived     sex   age  n_siblings_spouses  parch     fare   class  \
0         0    male  35.0                   0      0   8.0500   Third
1         0    male  54.0                   0      0  51.8625   First
2         1  female  58.0                   0      0  26.5500   First
3         1  female  55.0                   0      0  16.0000  Second
4         1    male  34.0                   0      0  13.0000  Second

      deck  embark_town alone
0  unknown  Southampton     y
1        E  Southampton     y
2        C  Southampton     y
3  unknown  Southampton     y
4        D  Southampton     y

In [4]:
y_train = train_df.pop('survived')
y_eval = eval_df.pop('survived')

print(train_df.head())
print(eval_df.head())
print(y_train.head())
print(y_eval.head())

      sex   age  n_siblings_spouses  parch     fare  class     deck  \
0    male  22.0                   1      0   7.2500  Third  unknown
1  female  38.0                   1      0  71.2833  First        C
2  female  26.0                   0      0   7.9250  Third  unknown
3  female  35.0                   1      0  53.1000  First        C
4    male  28.0                   0      0   8.4583  Third  unknown

   embark_town alone
0  Southampton     n
1    Cherbourg     n
2  Southampton     y
3  Southampton     n
4   Queenstown     y
      sex   age  n_siblings_spouses  parch     fare   class     deck  \
0    male  35.0                   0      0   8.0500   Third  unknown
1    male  54.0                   0      0  51.8625   First        E
2  female  58.0                   0      0  26.5500   First        C
3  female  55.0                   0      0  16.0000  Second  unknown
4    male  34.0                   0      0  13.0000  Second        D

   embark_town alone
0  Southampton     y
1  Southampton     y
2  Southampton     y
3  Southampton     y
4  Southampton     y
0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64
0    0
1    0
2    1
3    1
4    1
Name: survived, dtype: int64

In [5]:
train_df.describe()

              age  n_siblings_spouses       parch        fare
count  627.000000          627.000000  627.000000  627.000000
mean    29.631308            0.545455    0.379585   34.385399
std     12.511818            1.151090    0.792999   54.597730
min      0.750000            0.000000    0.000000    0.000000
25%     23.000000            0.000000    0.000000    7.895800
50%     28.000000            0.000000    0.000000   15.045800
75%     35.000000            1.000000    0.000000   31.387500
max     80.000000            8.000000    5.000000  512.329200

In [6]:
categorical_columns = ['sex', 'n_siblings_spouses', 'parch', 'class', 
                       'deck', 'embark_town', 'alone']
numeric_columns = ['age', 'fare']

feature_columns = []
for categorical_column in categorical_columns:
    vocab = train_df[categorical_column].unique()
    print(categorical_column, vocab)
    feature_columns.append(
        tf.feature_column.indicator_column(
            tf.feature_column.categorical_column_with_vocabulary_list(
                categorical_column, vocab)))

for numeric_column in numeric_columns:
    feature_columns.append(
        tf.feature_column.numeric_column(
            numeric_column, dtype=tf.float32))

from pprint import pprint
pprint(feature_columns)

sex ['male' 'female']
n_siblings_spouses [1 0 3 4 2 5 8]
parch [0 1 2 5 3 4]
class ['Third' 'First' 'Second']
deck ['unknown' 'C' 'G' 'A' 'B' 'D' 'F' 'E']
embark_town ['Southampton' 'Cherbourg' 'Queenstown' 'unknown']
alone ['n' 'y']
[IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='sex', vocabulary_list=('male', 'female'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='n_siblings_spouses', vocabulary_list=(1, 0, 3, 4, 2, 5, 8), dtype=tf.int64, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='parch', vocabulary_list=(0, 1, 2, 5, 3, 4), dtype=tf.int64, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='class', vocabulary_list=('Third', 'First', 'Second'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='deck', vocabulary_list=('unknown', 'C', 'G', 'A', 'B', 'D', 'F', 'E'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='embark_town', vocabulary_list=('Southampton', 'Cherbourg', 'Queenstown', 'unknown'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='alone', vocabulary_list=('n', 'y'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 NumericColumn(key='age', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='fare', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [10]:
def make_dataset(data_df, label_df, epochs = 10, shuffle = True, batch_size = 32):
    dataset = tf.data.Dataset.from_tensor_slices(
        (dict(data_df), label_df))
    if shuffle:
        dataset = dataset.shuffle(10000)
    dataset = dataset.repeat(epochs).batch(batch_size)
    return dataset.make_one_shot_iterator().get_next()

In [14]:
output_dir = 'customized_estimator'
if not os.path.exists(output_dir):
    os.mkdir(output_dir)

def model_fn(features, labels, mode, params):
    input_for_next_layer = tf.feature_column.input_layer(
        features, params['feature_columns'])
    
    for n_unit in params['hidden_units']:
         input_for_next_layer = tf.layers.dense(input_for_next_layer, units=n_unit, activation=tf.nn.relu)
    logits = tf.layers.dense(input_for_next_layer, params['n_classes'], activation=None)
    
    predicted_classes = tf.argmax(logits, 1)
    
    # model runtime state: Train, Eval, Predict
    if mode == tf.estimator.ModeKeys.PREDICT:
        predictions = {
            'class_ids': predicted_classes[:, tf.newaxis],
            'probabilities': tf.nn.softmax(logits),
            'logits': logits,
        }
        return tf.estimator.EstimatorSpec(mode, predictions=predictions)
    
    loss = tf.losses.sparse_softmax_cross_entropy(labels = labels, logits=logits)
    accuracy = tf.metrics.accuracy(labels = labels, predictions=predicted_classes, name='acc_op')
    metrics = {'accuracy': accuracy}
    
    if mode == tf.estimator.ModeKeys.EVAL:
        return tf.estimator.EstimatorSpec(mode, loss=loss, eval_metric_ops=metrics)
    
    optimizer = tf.train.AdadeltaOptimizer()
    train_op = optimizer.minimize(loss, global_step=tf.train.get_global_step())
    
#     if model == tf.estimator.ModeKeys.TRAIN:
    return tf.estimator.EstimatorSpec(mode, loss=loss, train_op=train_op)

estimator = tf.estimator.Estimator(
    model_fn = model_fn,
    model_dir = output_dir,
    params = {
        'feature_columns': feature_columns,
        'hidden_units': [100, 100],
        'n_classes': 2
    }
)

estimator.train(input_fn = lambda : make_dataset(train_df, y_train, epochs = 100))

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'customized_estimator', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f4b41584588>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into customized_estimator/model.ckpt.
INFO:tensorflow:loss = 1.7180705, step = 1
INFO:tensorflow:global_step/sec: 488.068
INFO:tensorflow:loss = 1.3608401, step = 101 (0.206 sec)
INFO:tensorflow:global_step/sec: 846.489
INFO:tensorflow:loss = 1.4626217, step = 201 (0.118 sec)
INFO:tensorflow:global_step/sec: 819.166
INFO:tensorflow:loss = 1.2485032, step = 301 (0.122 sec)
INFO:tensorflow:global_step/sec: 796.796
INFO:tensorflow:loss = 1.3336027, step = 401 (0.125 sec)
INFO:tensorflow:global_step/sec: 795.993
INFO:tensorflow:loss = 1.7069895, step = 501 (0.126 sec)
INFO:tensorflow:global_step/sec: 793.824
INFO:tensorflow:loss = 1.2479295, step = 601 (0.126 sec)
INFO:tensorflow:global_step/sec: 799.022
INFO:tensorflow:loss = 1.4177394, step = 701 (0.125 sec)
INFO:tensorflow:global_step/sec: 723.536
INFO:tensorflow:loss = 1.1936016, step = 801 (0.138 sec)
INFO:tensorflow:global_step/sec: 810.007
INFO:tensorflow:loss = 1.4446962, step = 901 (0.123 sec)
INFO:tensorflow:global_step/sec: 818.463
INFO:tensorflow:loss = 1.4740627, step = 1001 (0.122 sec)
INFO:tensorflow:global_step/sec: 804.3
INFO:tensorflow:loss = 1.214217, step = 1101 (0.124 sec)
INFO:tensorflow:global_step/sec: 860.368
INFO:tensorflow:loss = 1.3791584, step = 1201 (0.116 sec)
INFO:tensorflow:global_step/sec: 802.997
INFO:tensorflow:loss = 0.7654245, step = 1301 (0.125 sec)
INFO:tensorflow:global_step/sec: 788.566
INFO:tensorflow:loss = 0.8540356, step = 1401 (0.127 sec)
INFO:tensorflow:global_step/sec: 843.168
INFO:tensorflow:loss = 0.6637503, step = 1501 (0.118 sec)
INFO:tensorflow:global_step/sec: 783.945
INFO:tensorflow:loss = 0.7384284, step = 1601 (0.128 sec)
INFO:tensorflow:global_step/sec: 831.82
INFO:tensorflow:loss = 0.8809573, step = 1701 (0.120 sec)
INFO:tensorflow:global_step/sec: 853.842
INFO:tensorflow:loss = 1.0361452, step = 1801 (0.117 sec)
INFO:tensorflow:global_step/sec: 789.724
INFO:tensorflow:loss = 0.6533609, step = 1901 (0.127 sec)
INFO:tensorflow:Saving checkpoints for 1960 into customized_estimator/model.ckpt.
INFO:tensorflow:Loss for final step: 0.7301716.